# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """Définition du Service Inventaire écoutant sur le port 5006
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventoryByCafe = channel.unary_unary(
                '/inventory.InventoryService/GetInventoryByCafe',
                request_serializer=inventory__pb2.Empty.SerializeToString,
                response_deserializer=inventory__pb2.InventoryListResponse.FromString,
                _registered_method=True)
        self.UpdateInventoryAfterOrder = channel.unary_unary(
                '/inventory.InventoryService/UpdateInventoryAfterOrder',
                request_serializer=inventory__pb2.UpdateInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.UpdateInventoryResponse.FromString,
                _registered_method=True)
        self.RestockItem = channel.unary_unary(
                '/inventory.InventoryService/RestockItem',
                request_serializer=inventory__pb2.RestockItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.RestockItemResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Définition du Service Inventaire écoutant sur le port 5006
    """

    def GetInventoryByCafe(self, request, context):
        """Récupère la liste d'inventaire pour affichage dans le Frontend (Admin)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInventoryAfterOrder(self, request, context):
        """Met à jour le stock après une commande (Appel interne par Order Service)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestockItem(self, request, context):
        """Gère le réapprovisionnement (Appel par la Gateway suite à l'action Admin)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventoryByCafe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoryByCafe,
                    request_deserializer=inventory__pb2.Empty.FromString,
                    response_serializer=inventory__pb2.InventoryListResponse.SerializeToString,
            ),
            'UpdateInventoryAfterOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInventoryAfterOrder,
                    request_deserializer=inventory__pb2.UpdateInventoryRequest.FromString,
                    response_serializer=inventory__pb2.UpdateInventoryResponse.SerializeToString,
            ),
            'RestockItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RestockItem,
                    request_deserializer=inventory__pb2.RestockItemRequest.FromString,
                    response_serializer=inventory__pb2.RestockItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Définition du Service Inventaire écoutant sur le port 5006
    """

    @staticmethod
    def GetInventoryByCafe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetInventoryByCafe',
            inventory__pb2.Empty.SerializeToString,
            inventory__pb2.InventoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInventoryAfterOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/UpdateInventoryAfterOrder',
            inventory__pb2.UpdateInventoryRequest.SerializeToString,
            inventory__pb2.UpdateInventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestockItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/RestockItem',
            inventory__pb2.RestockItemRequest.SerializeToString,
            inventory__pb2.RestockItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
