# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import adminlogin_pb2 as adminlogin__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adminlogin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminLoginServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/adminlogin.AdminLoginService/Login',
                request_serializer=adminlogin__pb2.LoginRequest.SerializeToString,
                response_deserializer=adminlogin__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.UpdateAdminInfo = channel.unary_unary(
                '/adminlogin.AdminLoginService/UpdateAdminInfo',
                request_serializer=adminlogin__pb2.UpdateAdminRequest.SerializeToString,
                response_deserializer=adminlogin__pb2.UpdateAdminResponse.FromString,
                _registered_method=True)


class AdminLoginServiceServicer(object):
    """Service definition
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAdminInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminLoginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=adminlogin__pb2.LoginRequest.FromString,
                    response_serializer=adminlogin__pb2.LoginResponse.SerializeToString,
            ),
            'UpdateAdminInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAdminInfo,
                    request_deserializer=adminlogin__pb2.UpdateAdminRequest.FromString,
                    response_serializer=adminlogin__pb2.UpdateAdminResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adminlogin.AdminLoginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adminlogin.AdminLoginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminLoginService(object):
    """Service definition
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adminlogin.AdminLoginService/Login',
            adminlogin__pb2.LoginRequest.SerializeToString,
            adminlogin__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAdminInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adminlogin.AdminLoginService/UpdateAdminInfo',
            adminlogin__pb2.UpdateAdminRequest.SerializeToString,
            adminlogin__pb2.UpdateAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
