# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adminlogin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'adminlogin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x64minlogin.proto\x12\nadminlogin\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"C\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x61\x64min_id\x18\x03 \x01(\x05\"J\n\x12UpdateAdminRequest\x12\x10\n\x08\x61\x64min_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"7\n\x13UpdateAdminResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa5\x01\n\x11\x41\x64minLoginService\x12<\n\x05Login\x12\x18.adminlogin.LoginRequest\x1a\x19.adminlogin.LoginResponse\x12R\n\x0fUpdateAdminInfo\x12\x1e.adminlogin.UpdateAdminRequest\x1a\x1f.adminlogin.UpdateAdminResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adminlogin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=32
  _globals['_LOGINREQUEST']._serialized_end=82
  _globals['_LOGINRESPONSE']._serialized_start=84
  _globals['_LOGINRESPONSE']._serialized_end=151
  _globals['_UPDATEADMINREQUEST']._serialized_start=153
  _globals['_UPDATEADMINREQUEST']._serialized_end=227
  _globals['_UPDATEADMINRESPONSE']._serialized_start=229
  _globals['_UPDATEADMINRESPONSE']._serialized_end=284
  _globals['_ADMINLOGINSERVICE']._serialized_start=287
  _globals['_ADMINLOGINSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
