# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cafe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cafe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncafe.proto\x12\x04\x63\x61\x66\x65\"\x07\n\x05\x45mpty\"I\n\x04\x43\x61\x66\x65\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03nom\x18\x02 \x01(\t\x12\x14\n\x0clocalisation\x18\x03 \x01(\t\x12\x12\n\ncode_acces\x18\x04 \x01(\t\"-\n\x10\x43\x61\x66\x65ListResponse\x12\x19\n\x05\x63\x61\x66\x65s\x18\x01 \x03(\x0b\x32\n.cafe.Cafe\"J\n\x11\x43\x61\x66\x65\x43reateRequest\x12\x0b\n\x03nom\x18\x01 \x01(\t\x12\x14\n\x0clocalisation\x18\x02 \x01(\t\x12\x12\n\ncode_acces\x18\x03 \x01(\t\"V\n\x11\x43\x61\x66\x65UpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03nom\x18\x02 \x01(\t\x12\x14\n\x0clocalisation\x18\x03 \x01(\t\x12\x12\n\ncode_acces\x18\x04 \x01(\t\"\x1f\n\x11\x43\x61\x66\x65\x44\x65leteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"s\n\x0c\x43\x61\x66\x65Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0b\n\x03nom\x18\x04 \x01(\t\x12\x14\n\x0clocalisation\x18\x05 \x01(\t\x12\x12\n\ncode_acces\x18\x06 \x01(\t\"+\n\x15\x43\x61\x66\x65VerifyCodeRequest\x12\x12\n\ncode_acces\x18\x01 \x01(\t\"n\n\x16\x43\x61\x66\x65VerifyCodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x03 \x01(\x05\x12\x0b\n\x03nom\x18\x04 \x01(\t\x12\x14\n\x0clocalisation\x18\x05 \x01(\t2\xbf\x02\n\x0b\x43\x61\x66\x65Service\x12\x32\n\x0bGetAllCafes\x12\x0b.cafe.Empty\x1a\x16.cafe.CafeListResponse\x12\x39\n\nCreateCafe\x12\x17.cafe.CafeCreateRequest\x1a\x12.cafe.CafeResponse\x12\x39\n\nUpdateCafe\x12\x17.cafe.CafeUpdateRequest\x1a\x12.cafe.CafeResponse\x12\x39\n\nDeleteCafe\x12\x17.cafe.CafeDeleteRequest\x1a\x12.cafe.CafeResponse\x12K\n\x0eVerifyCafeCode\x12\x1b.cafe.CafeVerifyCodeRequest\x1a\x1c.cafe.CafeVerifyCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cafe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CAFE']._serialized_start=29
  _globals['_CAFE']._serialized_end=102
  _globals['_CAFELISTRESPONSE']._serialized_start=104
  _globals['_CAFELISTRESPONSE']._serialized_end=149
  _globals['_CAFECREATEREQUEST']._serialized_start=151
  _globals['_CAFECREATEREQUEST']._serialized_end=225
  _globals['_CAFEUPDATEREQUEST']._serialized_start=227
  _globals['_CAFEUPDATEREQUEST']._serialized_end=313
  _globals['_CAFEDELETEREQUEST']._serialized_start=315
  _globals['_CAFEDELETEREQUEST']._serialized_end=346
  _globals['_CAFERESPONSE']._serialized_start=348
  _globals['_CAFERESPONSE']._serialized_end=463
  _globals['_CAFEVERIFYCODEREQUEST']._serialized_start=465
  _globals['_CAFEVERIFYCODEREQUEST']._serialized_end=508
  _globals['_CAFEVERIFYCODERESPONSE']._serialized_start=510
  _globals['_CAFEVERIFYCODERESPONSE']._serialized_end=620
  _globals['_CAFESERVICE']._serialized_start=623
  _globals['_CAFESERVICE']._serialized_end=942
# @@protoc_insertion_point(module_scope)
