# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cafe_pb2 as cafe__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cafe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CafeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllCafes = channel.unary_unary(
                '/cafe.CafeService/GetAllCafes',
                request_serializer=cafe__pb2.Empty.SerializeToString,
                response_deserializer=cafe__pb2.CafeListResponse.FromString,
                _registered_method=True)
        self.CreateCafe = channel.unary_unary(
                '/cafe.CafeService/CreateCafe',
                request_serializer=cafe__pb2.CafeCreateRequest.SerializeToString,
                response_deserializer=cafe__pb2.CafeResponse.FromString,
                _registered_method=True)
        self.UpdateCafe = channel.unary_unary(
                '/cafe.CafeService/UpdateCafe',
                request_serializer=cafe__pb2.CafeUpdateRequest.SerializeToString,
                response_deserializer=cafe__pb2.CafeResponse.FromString,
                _registered_method=True)
        self.DeleteCafe = channel.unary_unary(
                '/cafe.CafeService/DeleteCafe',
                request_serializer=cafe__pb2.CafeDeleteRequest.SerializeToString,
                response_deserializer=cafe__pb2.CafeResponse.FromString,
                _registered_method=True)
        self.VerifyCafeCode = channel.unary_unary(
                '/cafe.CafeService/VerifyCafeCode',
                request_serializer=cafe__pb2.CafeVerifyCodeRequest.SerializeToString,
                response_deserializer=cafe__pb2.CafeVerifyCodeResponse.FromString,
                _registered_method=True)


class CafeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllCafes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCafe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCafe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCafe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCafeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CafeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllCafes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCafes,
                    request_deserializer=cafe__pb2.Empty.FromString,
                    response_serializer=cafe__pb2.CafeListResponse.SerializeToString,
            ),
            'CreateCafe': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCafe,
                    request_deserializer=cafe__pb2.CafeCreateRequest.FromString,
                    response_serializer=cafe__pb2.CafeResponse.SerializeToString,
            ),
            'UpdateCafe': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCafe,
                    request_deserializer=cafe__pb2.CafeUpdateRequest.FromString,
                    response_serializer=cafe__pb2.CafeResponse.SerializeToString,
            ),
            'DeleteCafe': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCafe,
                    request_deserializer=cafe__pb2.CafeDeleteRequest.FromString,
                    response_serializer=cafe__pb2.CafeResponse.SerializeToString,
            ),
            'VerifyCafeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCafeCode,
                    request_deserializer=cafe__pb2.CafeVerifyCodeRequest.FromString,
                    response_serializer=cafe__pb2.CafeVerifyCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafe.CafeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cafe.CafeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CafeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllCafes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cafe.CafeService/GetAllCafes',
            cafe__pb2.Empty.SerializeToString,
            cafe__pb2.CafeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCafe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cafe.CafeService/CreateCafe',
            cafe__pb2.CafeCreateRequest.SerializeToString,
            cafe__pb2.CafeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCafe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cafe.CafeService/UpdateCafe',
            cafe__pb2.CafeUpdateRequest.SerializeToString,
            cafe__pb2.CafeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCafe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cafe.CafeService/DeleteCafe',
            cafe__pb2.CafeDeleteRequest.SerializeToString,
            cafe__pb2.CafeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCafeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cafe.CafeService/VerifyCafeCode',
            cafe__pb2.CafeVerifyCodeRequest.SerializeToString,
            cafe__pb2.CafeVerifyCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
