# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x07\n\x05\x45mpty\"T\n\x16UpdateInventoryRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x02 \x01(\t\x12\x18\n\x10quantity_ordered\x18\x03 \x01(\x05\"d\n\x12RestockItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x02 \x01(\t\x12\x16\n\x0equantity_added\x18\x03 \x01(\x05\x12\x14\n\x0crestock_date\x18\x04 \x01(\t\";\n\x17UpdateInventoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x13RestockItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x9b\x01\n\rInventoryItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x02 \x01(\t\x12\x11\n\titem_name\x18\x03 \x01(\t\x12\x11\n\tcafe_name\x18\x04 \x01(\t\x12\x16\n\x0estock_quantity\x18\x05 \x01(\x05\x12\x14\n\x0crestock_date\x18\x06 \x01(\t\x12\x14\n\x0cis_low_stock\x18\x07 \x01(\x08\"@\n\x15InventoryListResponse\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.inventory.InventoryItem2\x8e\x02\n\x10InventoryService\x12H\n\x12GetInventoryByCafe\x12\x10.inventory.Empty\x1a .inventory.InventoryListResponse\x12\x62\n\x19UpdateInventoryAfterOrder\x12!.inventory.UpdateInventoryRequest\x1a\".inventory.UpdateInventoryResponse\x12L\n\x0bRestockItem\x12\x1d.inventory.RestockItemRequest\x1a\x1e.inventory.RestockItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_UPDATEINVENTORYREQUEST']._serialized_start=39
  _globals['_UPDATEINVENTORYREQUEST']._serialized_end=123
  _globals['_RESTOCKITEMREQUEST']._serialized_start=125
  _globals['_RESTOCKITEMREQUEST']._serialized_end=225
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_start=227
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_end=286
  _globals['_RESTOCKITEMRESPONSE']._serialized_start=288
  _globals['_RESTOCKITEMRESPONSE']._serialized_end=343
  _globals['_INVENTORYITEM']._serialized_start=346
  _globals['_INVENTORYITEM']._serialized_end=501
  _globals['_INVENTORYLISTRESPONSE']._serialized_start=503
  _globals['_INVENTORYLISTRESPONSE']._serialized_end=567
  _globals['_INVENTORYSERVICE']._serialized_start=570
  _globals['_INVENTORYSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
