# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\"\x0e\n\x0c\x45mptyRequest\"4\n\x0cLoginRequest\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61\x63\x63\x65ss_code\x18\x02 \x01(\t\"U\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x03 \x01(\x05\x12\x11\n\tcafe_name\x18\x04 \x01(\t\"2\n\x04\x43\x61\x66\x65\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\".\n\x10\x43\x61\x66\x65ListResponse\x12\x1a\n\x05\x63\x61\x66\x65s\x18\x01 \x03(\x0b\x32\x0b.login.Cafe2\x8a\x01\n\x0cLoginService\x12=\n\x10\x41uthenticateCafe\x12\x13.login.LoginRequest\x1a\x14.login.LoginResponse\x12;\n\x0bGetAllCafes\x12\x13.login.EmptyRequest\x1a\x17.login.CafeListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=22
  _globals['_EMPTYREQUEST']._serialized_end=36
  _globals['_LOGINREQUEST']._serialized_start=38
  _globals['_LOGINREQUEST']._serialized_end=90
  _globals['_LOGINRESPONSE']._serialized_start=92
  _globals['_LOGINRESPONSE']._serialized_end=177
  _globals['_CAFE']._serialized_start=179
  _globals['_CAFE']._serialized_end=229
  _globals['_CAFELISTRESPONSE']._serialized_start=231
  _globals['_CAFELISTRESPONSE']._serialized_end=277
  _globals['_LOGINSERVICE']._serialized_start=280
  _globals['_LOGINSERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
