# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import menu_pb2 as menu__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in menu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MenuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMenuItem = channel.unary_unary(
                '/menu.MenuService/AddMenuItem',
                request_serializer=menu__pb2.MenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)
        self.GetMenuItems = channel.unary_unary(
                '/menu.MenuService/GetMenuItems',
                request_serializer=menu__pb2.Empty.SerializeToString,
                response_deserializer=menu__pb2.MenuItemsResponse.FromString,
                _registered_method=True)
        self.UpdateMenuItem = channel.unary_unary(
                '/menu.MenuService/UpdateMenuItem',
                request_serializer=menu__pb2.MenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)
        self.DeleteMenuItem = channel.unary_unary(
                '/menu.MenuService/DeleteMenuItem',
                request_serializer=menu__pb2.MenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.DeleteResponse.FromString,
                _registered_method=True)


class MenuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMenuItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MenuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMenuItem,
                    request_deserializer=menu__pb2.MenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
            'GetMenuItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMenuItems,
                    request_deserializer=menu__pb2.Empty.FromString,
                    response_serializer=menu__pb2.MenuItemsResponse.SerializeToString,
            ),
            'UpdateMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMenuItem,
                    request_deserializer=menu__pb2.MenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
            'DeleteMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMenuItem,
                    request_deserializer=menu__pb2.MenuItemRequest.FromString,
                    response_serializer=menu__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'menu.MenuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('menu.MenuService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MenuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menu.MenuService/AddMenuItem',
            menu__pb2.MenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMenuItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menu.MenuService/GetMenuItems',
            menu__pb2.Empty.SerializeToString,
            menu__pb2.MenuItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menu.MenuService/UpdateMenuItem',
            menu__pb2.MenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menu.MenuService/DeleteMenuItem',
            menu__pb2.MenuItemRequest.SerializeToString,
            menu__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
