# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: menu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'menu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmenu.proto\x12\x04menu\"\x07\n\x05\x45mpty\"L\n\x0fMenuItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"M\n\x10MenuItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\":\n\x11MenuItemsResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.menu.MenuItemResponse\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x81\x02\n\x0bMenuService\x12<\n\x0b\x41\x64\x64MenuItem\x12\x15.menu.MenuItemRequest\x1a\x16.menu.MenuItemResponse\x12\x34\n\x0cGetMenuItems\x12\x0b.menu.Empty\x1a\x17.menu.MenuItemsResponse\x12?\n\x0eUpdateMenuItem\x12\x15.menu.MenuItemRequest\x1a\x16.menu.MenuItemResponse\x12=\n\x0e\x44\x65leteMenuItem\x12\x15.menu.MenuItemRequest\x1a\x14.menu.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_MENUITEMREQUEST']._serialized_start=29
  _globals['_MENUITEMREQUEST']._serialized_end=105
  _globals['_MENUITEMRESPONSE']._serialized_start=107
  _globals['_MENUITEMRESPONSE']._serialized_end=184
  _globals['_MENUITEMSRESPONSE']._serialized_start=186
  _globals['_MENUITEMSRESPONSE']._serialized_end=244
  _globals['_DELETERESPONSE']._serialized_start=246
  _globals['_DELETERESPONSE']._serialized_end=279
  _globals['_MENUSERVICE']._serialized_start=282
  _globals['_MENUSERVICE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
