# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"F\n\x12\x43reateOrderRequest\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x01 \x01(\t\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.order.OrderItem\"=\n\tOrderItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"^\n\x13\x43reateOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x13\n\x0btotal_price\x18\x04 \x01(\x01\"#\n\x10GetOrdersRequest\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x01 \x01(\t\"t\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61\x66\x65_id\x18\x02 \x01(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x01\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x1f\n\x05items\x18\x05 \x03(\x0b\x32\x10.order.OrderItem\".\n\x0eOrdersResponse\x12\x1c\n\x06orders\x18\x01 \x03(\x0b\x32\x0c.order.Order2\x97\x01\n\x0cOrderService\x12\x44\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12\x41\n\x0fGetOrdersByCafe\x12\x17.order.GetOrdersRequest\x1a\x15.order.OrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=22
  _globals['_CREATEORDERREQUEST']._serialized_end=92
  _globals['_ORDERITEM']._serialized_start=94
  _globals['_ORDERITEM']._serialized_end=155
  _globals['_CREATEORDERRESPONSE']._serialized_start=157
  _globals['_CREATEORDERRESPONSE']._serialized_end=251
  _globals['_GETORDERSREQUEST']._serialized_start=253
  _globals['_GETORDERSREQUEST']._serialized_end=288
  _globals['_ORDER']._serialized_start=290
  _globals['_ORDER']._serialized_end=406
  _globals['_ORDERSRESPONSE']._serialized_start=408
  _globals['_ORDERSRESPONSE']._serialized_end=454
  _globals['_ORDERSERVICE']._serialized_start=457
  _globals['_ORDERSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
