# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import analytics_pb2 as proto_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """------------ END NEW ------------ 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCardMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCardMetrics',
                request_serializer=proto_dot_analytics__pb2.MonthRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.CardMetrics.FromString,
                _registered_method=True)
        self.GetOverviewAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetOverviewAnalytics',
                request_serializer=proto_dot_analytics__pb2.MonthRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.OverviewAnalytics.FromString,
                _registered_method=True)
        self.GetPredictions = channel.unary_unary(
                '/analytics.AnalyticsService/GetPredictions',
                request_serializer=proto_dot_analytics__pb2.PredictionRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.PredictionResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """------------ END NEW ------------ 

    """

    def GetCardMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverviewAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictions(self, request, context):
        """NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCardMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCardMetrics,
                    request_deserializer=proto_dot_analytics__pb2.MonthRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.CardMetrics.SerializeToString,
            ),
            'GetOverviewAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverviewAnalytics,
                    request_deserializer=proto_dot_analytics__pb2.MonthRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.OverviewAnalytics.SerializeToString,
            ),
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=proto_dot_analytics__pb2.PredictionRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """------------ END NEW ------------ 

    """

    @staticmethod
    def GetCardMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCardMetrics',
            proto_dot_analytics__pb2.MonthRequest.SerializeToString,
            proto_dot_analytics__pb2.CardMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverviewAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetOverviewAnalytics',
            proto_dot_analytics__pb2.MonthRequest.SerializeToString,
            proto_dot_analytics__pb2.OverviewAnalytics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetPredictions',
            proto_dot_analytics__pb2.PredictionRequest.SerializeToString,
            proto_dot_analytics__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
